# Generated by Django 5.1.2 on 2024-12-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitation",
            name="axles",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="calc_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="calc_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="created_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="destination_farm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="equipment_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="last_edited_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="origin_farm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="request",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="reservation_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="reservation_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="reservation_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="x_coordinate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitation",
            name="y_coordinate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
