# Generated by Django 5.1.2 on 2024-12-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_solicitation_axles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("btf_01", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Escala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frota", models.CharField(max_length=50)),
                ("placa", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=255)),
                ("matricula", models.IntegerField()),
                ("colaborador_dia", models.CharField(max_length=255)),
                ("workday", models.FloatField(blank=True, null=True)),
                ("admissao", models.DateTimeField()),
                ("ferias", models.CharField(blank=True, max_length=255, null=True)),
                ("contato", models.CharField(blank=True, max_length=255, null=True)),
                ("letra", models.CharField(max_length=10)),
                ("horario", models.CharField(max_length=50)),
                ("matricula_noite", models.FloatField(blank=True, null=True)),
                ("colaborador_noite", models.CharField(max_length=255)),
                ("workday2", models.FloatField(blank=True, null=True)),
                ("admissao_noite", models.DateTimeField(blank=True, null=True)),
                (
                    "ferias_noite",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contato_noite",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("letra2", models.CharField(max_length=10)),
                ("horario_noite", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Pranchas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quan", models.IntegerField()),
                ("frota", models.IntegerField()),
                ("placa", models.CharField(max_length=50)),
                ("fabricante", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                ("especificacoes", models.TextField()),
                ("chassis", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tritrem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("btf_01", models.IntegerField()),
                ("placa", models.CharField(max_length=50)),
                ("primeira_carreta", models.CharField(max_length=50)),
                ("segunda_carreta", models.CharField(max_length=50)),
                ("terceira_carreta", models.CharField(max_length=50)),
                ("fabricante_cm", models.CharField(max_length=100)),
                ("fabricante_conjunto", models.CharField(max_length=100)),
            ],
        ),
    ]
