# Generated by Django 5.1.2 on 2024-12-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_btf_01_cm_btf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="escala", old_name="colaborador_noite", new_name="colaborador",
        ),
        migrations.RemoveField(model_name="escala", name="admissao_noite",),
        migrations.RemoveField(model_name="escala", name="colaborador_dia",),
        migrations.RemoveField(model_name="escala", name="contato_noite",),
        migrations.RemoveField(model_name="escala", name="ferias_noite",),
        migrations.RemoveField(model_name="escala", name="horario_noite",),
        migrations.RemoveField(model_name="escala", name="letra2",),
        migrations.RemoveField(model_name="escala", name="matricula_noite",),
        migrations.RemoveField(model_name="escala", name="workday2",),
        migrations.AddField(
            model_name="escala",
            name="periodo",
            field=models.CharField(
                choices=[("DIA", "Dia"), ("NOITE", "Noite")],
                default="DIA",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="escala", name="admissao", field=models.DateField(),
        ),
    ]
