# Generated by Django 5.1.2 on 2024-12-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_colaborador_noite_escala_colaborador_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalaDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frota", models.CharField(max_length=255)),
                ("placa", models.CharField(max_length=255)),
                ("descricao", models.CharField(max_length=255)),
                ("matricula", models.BigIntegerField()),
                ("colaborador", models.CharField(max_length=255)),
                ("workday", models.FloatField(blank=True, null=True)),
                ("admissao", models.DateField(blank=True, null=True)),
                ("ferias", models.CharField(blank=True, max_length=255, null=True)),
                ("contato", models.CharField(blank=True, max_length=255, null=True)),
                ("letra", models.CharField(max_length=10)),
                ("horario", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EscalaNoite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frota", models.CharField(max_length=255)),
                ("placa", models.CharField(max_length=255)),
                ("descricao", models.CharField(max_length=255)),
                ("matricula", models.BigIntegerField()),
                ("colaborador", models.CharField(max_length=255)),
                ("workday", models.FloatField(blank=True, null=True)),
                ("admissao", models.DateField(blank=True, null=True)),
                ("ferias", models.CharField(blank=True, max_length=255, null=True)),
                ("contato", models.CharField(blank=True, max_length=255, null=True)),
                ("letra", models.CharField(max_length=10)),
                ("horario", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(name="Escala",),
    ]
